cmake_minimum_required(VERSION 4.0)
project(Question_5)

set(CMAKE_CXX_STANDARD 20)

add_executable(Question_5 main.cpp
        "Aditional Library/BSTFunctions.cpp"
        "Aditional Library/BSTFunctions.h"
        "Aditional Library/BSTNode.h"
        "Aditional Library/BSTElement.h"
        "Aditional Library/BST.h")
